name: Build and deploy ASP.Net Core app to Azure Web App - AdvancedDevelopment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build ./AdvancedDevelopment/AdvancedDevelopment.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish ./AdvancedDevelopment/AdvancedDevelopment.sln -c Release -o ${{ env.DOTNET_ROOT }}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E14AACDF163943059EB72A33578533B0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_32CB3F699EAD4310B63B7A5A7276A51F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5849D9DC359B45EA813CBAED41CD01A1 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'GasAdvancedDevelopment'
          slot-name: 'Production'
          package: .

